In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.reshape(2, -1)

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
a.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
b.shape

(2, 3)

In [21]:
w = pd.DataFrame([ 1.66e+00,  2.38e-01 , 9.25e-02,  6.89e-02 , 1.81e-02 , 1.55e-02 , 2.41e-02,
  3.58e-03 , 2.98e-02 , 1.02e+00  ,1.68e-04, -9.25e-04 , 3.77e-02,  9.09e-01,
  1.06e-02  ,2.16e-01,  3.26e-04,  4.23e-04,-1.66e-03])


In [28]:
w.apply(lambda a: a if a.item() > 0.0 else 0.0)

ValueError: can only convert an array of size 1 to a Python scalar

In [37]:
w.apply(lambda a : a + a)

0
0   3.320000
1   0.476000
2   0.185000
3   0.137800
4   0.036200
5   0.031000
6   0.048200
7   0.007160
8   0.059600
9   2.040000
10  0.000336
11 -0.001850
12  0.075400
13  1.818000
14  0.021200
15  0.432000
16  0.000652
17  0.000846
18 -0.003320